### ISSUE TITLE
ubuntu20 python3.8 unable to install jamspell using pip

### ISSUE THREAD

**Issue by abramovi** [bakwc/JamSpell#103]
Unable to install jamspell using pip

`pip install jamspell
 ---> Running in fae481cd8eb2
Collecting jamspell
  Downloading jamspell-0.0.11.tar.gz (60 kB)
Building wheels for collected packages: jamspell
  Building wheel for jamspell (setup.py): started
  Building wheel for jamspell (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-55wf5d8y/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-55wf5d8y/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z7ezb1wb
       cwd: /tmp/pip-install-55wf5d8y/jamspell/
  Complete output (123 lines):
  running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  swigging jamspell.i to jamspell_wrap.cpp
  /usr/bin/swig3.0 -python -c++ -o jamspell_wrap.cpp jamspell.i
  creating build
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/jamspell
  creating build/temp.linux-x86_64-3.8/contrib
  creating build/temp.linux-x86_64-3.8/contrib/cityhash
  creating build/temp.linux-x86_64-3.8/contrib/phf
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c jamspell/lang_model.cpp -o build/temp.linux-x86_64-3.8/jamspell/lang_model.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c jamspell/spell_corrector.cpp -o build/temp.linux-x86_64-3.8/jamspell/spell_corrector.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c jamspell/utils.cpp -o build/temp.linux-x86_64-3.8/jamspell/utils.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c jamspell/perfect_hash.cpp -o build/temp.linux-x86_64-3.8/jamspell/perfect_hash.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c jamspell/bloom_filter.cpp -o build/temp.linux-x86_64-3.8/jamspell/bloom_filter.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c contrib/cityhash/city.cc -o build/temp.linux-x86_64-3.8/contrib/cityhash/city.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c contrib/phf/phf.cc -o build/temp.linux-x86_64-3.8/contrib/phf/phf.o -std=c++11 -O2
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -Ijamspell -I/usr/include/python3.8 -c jamspell_wrap.cpp -o build/temp.linux-x86_64-3.8/jamspell_wrap.o -std=c++11 -O2
  jamspell_wrap.cpp: In function ‘int SWIG_AsWCharPtrAndSize(PyObject*, wchar_t**, size_t*, int*)’:
  jamspell_wrap.cpp:4728:43: warning: ‘Py_ssize_t PyUnicode_GetSize(PyObject*)’ is deprecated [-Wdeprecated-declarations]
   4728 |     Py_ssize_t len = PyUnicode_GetSize(obj);
        |                                           ^
  In file included from /usr/include/python3.8/Python.h:97,
                   from jamspell_wrap.cpp:173:
  /usr/include/python3.8/unicodeobject.h:177:43: note: declared here
    177 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_ssize_t) PyUnicode_GetSize(
        |                                           ^~~~~~~~~~~~~~~~~
  jamspell_wrap.cpp:4728:43: warning: ‘Py_ssize_t PyUnicode_GetSize(PyObject*)’ is deprecated [-Wdeprecated-declarations]
   4728 |     Py_ssize_t len = PyUnicode_GetSize(obj);
        |                                           ^
  In file included from /usr/include/python3.8/Python.h:97,
                   from jamspell_wrap.cpp:173:
  /usr/include/python3.8/unicodeobject.h:177:43: note: declared here
    177 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_ssize_t) PyUnicode_GetSize(
        |                                           ^~~~~~~~~~~~~~~~~
  creating build/lib.linux-x86_64-3.8
  x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/jamspell/lang_model.o build/temp.linux-x86_64-3.8/jamspell/spell_corrector.o build/temp.linux-x86_64-3.8/jamspell/utils.o build/temp.linux-x86_64-3.8/jamspell/perfect_hash.o build/temp.linux-x86_64-3.8/jamspell/bloom_filter.o build/temp.linux-x86_64-3.8/contrib/cityhash/city.o build/temp.linux-x86_64-3.8/contrib/phf/phf.o build/temp.linux-x86_64-3.8/jamspell_wrap.o -o build/lib.linux-x86_64-3.8/_jamspell.cpython-38-x86_64-linux-gnu.so
  running build_py
  copying jamspell.py -> build/lib.linux-x86_64-3.8
  running egg_info
  writing jamspell.egg-info/PKG-INFO
  writing dependency_links to jamspell.egg-info/dependency_links.txt
  writing top-level names to jamspell.egg-info/top_level.txt
  reading manifest file 'jamspell.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'jamspell.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  Checking .pth file support in build/bdist.linux-x86_64/wheel/
  /usr/bin/python3 -E -c pass
  TEST FAILED: build/bdist.linux-x86_64/wheel/ does NOT support .pth files
  bad install directory or PYTHONPATH
  
  You are attempting to install a package to a directory that is not
  on PYTHONPATH and which Python does not read ".pth" files from.  The
  installation directory you specified (via --install-dir, --prefix, or
  the distutils default setting) was:
  
      build/bdist.linux-x86_64/wheel/
  
  and your PYTHONPATH environment variable currently contains:
  
      ''
  
  Here are some of your options for correcting the problem:
  
  * You can choose a different installation directory, i.e., one that is
    on PYTHONPATH or supports .pth files
  
  * You can add the installation directory to the PYTHONPATH environment
    variable.  (It must then also be on PYTHONPATH whenever you run
    Python and want to use the package(s) you are installing.)
  
  * You can set up the installation directory to support ".pth" files by
    using one of the approaches described here:
  
    https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
  
  
  Please make the appropriate changes for your system and try again.
  running bdist_egg
  installing library code to build/bdist.linux-x86_64/egg
  running install_lib
  creating build/bdist.linux-x86_64/egg
  copying build/lib.linux-x86_64-3.8/_jamspell.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
  copying build/lib.linux-x86_64-3.8/jamspell.py -> build/bdist.linux-x86_64/egg
  creating stub loader for _jamspell.cpython-38-x86_64-linux-gnu.so
  creating build/bdist.linux-x86_64/egg/EGG-INFO
  copying jamspell.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying jamspell.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying jamspell.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying jamspell.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
  copying jamspell.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
  writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
  creating dist
  creating 'dist/jamspell-0.0.11-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
  removing 'build/bdist.linux-x86_64/egg' (and everything under it)
  Processing jamspell-0.0.11-py3.8-linux-x86_64.egg
  creating /tmp/pip-install-55wf5d8y/jamspell/build/bdist.linux-x86_64/wheel/jamspell-0.0.11-py3.8-linux-x86_64.egg
  Extracting jamspell-0.0.11-py3.8-linux-x86_64.egg to /tmp/pip-install-55wf5d8y/jamspell/build/bdist.linux-x86_64/wheel
  
  Installed /tmp/pip-install-55wf5d8y/jamspell/build/bdist.linux-x86_64/wheel/jamspell-0.0.11-py3.8-linux-x86_64.egg
  Processing dependencies for jamspell==0.0.11
  Finished processing dependencies for jamspell==0.0.11
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-55wf5d8y/jamspell/setup.py", line 51, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 275, in run
      self.egg2dist(self.egginfo_dir, distinfo_dir)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 372, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.linux-x86_64/egg/jamspell-0.0.11.egg-info but not found
  ----------------------------------------
  ERROR: Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
DEPRECATION: Could not build wheels for jamspell which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: jamspell
    Running setup.py install for jamspell: started
    Running setup.py install for jamspell: finished with status 'done'
ERROR: jamspell did not indicate that it installed an .egg-info directory. Only setup.py projects generating .egg-info directories are supported.
The command '/bin/sh -c pip install jamspell' returned a non-zero code: 1`

**Comment by alex1648factory** [comment]
same here... wondering no responses here for 2 years

**Comment by bakwc** [comment]
Are you installing with `sudo`? There is "Ubuntu 20.04.5 LTS" inside google colab, there is a step by step commands there:
https://colab.research.google.com/drive/1aFk8-7nq3oAp402jjLGLpEb2Nzq210Eo#scrollTo=NOqWwqBLYTSt
And everything works fine. If you need a dedicated support to figure out what's the issue with installing on your environment - you can purchase a "Pro" version.
