### ISSUE TITLE
Russian model not working

### ISSUE THREAD

**Issue by not-solemn-leader** [bakwc/JamSpell#105]
I've done everything that was written in README and tried to use russian model like in Python usage example:
```import jamspell

corrector = jamspell.TSpellCorrector()
corrector.LoadLangModel('ru_small.bin')

corrector.GetCandidates(['я', 'не', 'хотю'], 5)
# ()
```

but the final line always returns empty brackets `()` whatever the input is. Am I doing smth wrong or it's a bug?

P.S.
English model works just fine

**Comment by bakwc** [comment]
`corrector.GetCandidates(['я', 'не', 'хотю'], 5)`
5 - it is a word number you want to correct. There is only 3 words, so you should pass 0, 1 or 2 as a last argument.
