### ISSUE TITLE
unable to install in mac and also in colab

### ISSUE THREAD

**Issue by ajay-sreeram** [bakwc/JamSpell#106]
throwing error

`ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xujmxfpq/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xujmxfpq/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z3nifwwn/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
`

**Comment by bakwc** [comment]
https://colab.research.google.com/drive/1aFk8-7nq3oAp402jjLGLpEb2Nzq210Eo?usp=sharing

**Comment by ajay-sreeram** [comment]
Thank you @bakwc
