### ISSUE TITLE
Hangs up when calling TSpellCorrector.LoadLangModel

### ISSUE THREAD

**Issue by doctor3030** [bakwc/JamSpell#108]
When running the following code:

`# Example

import jamspell
corrector_en = jamspell.TSpellCorrector()
corrector_en.LoadLangModel('path')
res = corrector_en.FixFragment('buyy carr')
print(res)`

I have my proccess hanged up after getting to corrector_en.LoadLangModel('path').
The 'path' here is just a path to the en.bin model on the hard drive.

I'm using python 3.7 and jamspell 0.0.12.
I have also tried to install swig & swigwin versions 3.0.12 and 4.0.2.

Since it just hangs up and doesn't give any error message, I can't figure out the problem. But maybe it is something related to C++ libraries?

I appreciate any help.
Thanks

**Comment by bakwc** [comment]
Does lang model successfully loaded? Could you print the result of LoadLangModel function?
first time model loads can take a while (several minutes) - it generates caches

**Comment by bakwc** [comment]
What OS? Have you tried to wait longer (15-30 minutes?)

**Comment by doctor3030** [comment]
OS is Windows 10.
I gave it more than an hour today and it didn't work.

**Comment by bakwc** [comment]
Community version may have issues on windows (models trained on linux does not work on windows).
Full windows support available at "[Pro](https://jamspell.com/)" version.

**Comment by fRedelaar** [comment]
Did someone ever find a solution for this? (Windows 10)

**Comment by MasterKavi-24** [comment]
@bakwc, what can Community users do for this issue ? If Linux trained models aren't compatible with Windows 10, are there any other sources of model files for Windows 10 ?

**Comment by bakwc** [comment]
Option 1: Train your own community model on windows and upload it somewhere and add links (here or in README.md). You can use wikipedia dump, you can download it from [Leipzig Corpora Collection](http://wortschatz.uni-leipzig.de/en/download/) as well as news and other source.

Option 2: Fix the issue with loading Linux model on windows, make a fix and create PR to help others, if someone create this fix it will be accepted - so others could be able to use a single model in a community version.

Option 3: Buy a Pro version - it includes a small, medium and large models for a lot of languages with the increased quality and it handles more error cases, eg. words splitting.
