### ISSUE TITLE
How can we know if some word contains mistake?

### ISSUE THREAD

**Issue by AlexKrimi** [bakwc/JamSpell#11]
jamspell gives nice suggestions, but how can i be sure that it gives suggestions only for "wrong" words?

**Comment by bakwc** [comment]
What do you mean? If jamspell returns suggestions and first suggestion is not the original word - it means that jamspell consider current word broken.
According to [benchmarks](https://github.com/bakwc/JamSpell#benchmarks), attached simple english model brokes less then 1% of correct words.

**Comment by AlexKrimi** [comment]
Oh i thought jamspell has method like `corrector.has_mistakes(some_word)` which returns boolean, but if the original is always first one in suggestions that is great! 
Would be cool to see this in documentation, thanks!
