### ISSUE TITLE
Spanish model

### ISSUE THREAD

**Issue by carlosalbertonascimento** [bakwc/JamSpell#111]
Hi, 

How can I download the spanish model?

**Comment by bakwc** [comment]
Good pre-trained spanish model available in "Pro" version.
You can [purchase a "Pro" version](https://store.payproglobal.com/checkout?products[1][id]=61441&currency=USD) or you can [train](https://github.com/bakwc/JamSpell#train) Spanish model yourself

**Comment by carlosalbertonascimento** [comment]
Thank you
