### ISSUE TITLE
Jamspell Pro

### ISSUE THREAD

**Issue by bino282** [bakwc/JamSpell#117]
I want to use jamspell pro version but there is no Vietnamese version. I looked on jamspell.com, the price for the pro version is 40$. In this version, do you have a release code to train with other languages?

**Comment by bakwc** [comment]
Sure, there is a training code and instructions. But you will have to gather a training corpus yourself - we don't have a Vietnam text corpus.

**Comment by bino282** [comment]
yes. How can I pay for the pro version?

**Comment by bakwc** [comment]
With a card or PayPall. Just press "Buy Now" on https://jamspell.com/ and enter the details.
