### ISSUE TITLE
try to install to windows but not running 

### ISSUE THREAD

**Issue by OWaheed** [bakwc/JamSpell#121]
I installed Swig 3.0.0 and added it to the PATH list and I used python 3.7 and 3.8 and tried to install using pip install but there is always an error 
I have visual studio latest version installed and Microsoft C++ Build Tools

and I tried to use colab instead it run but when increasing the data the model stop learning and print 
![image](https://user-images.githubusercontent.com/34371827/167272184-165597bf-5fd8-4638-a114-e5f86b6063ec.png)

**Comment by bakwc** [comment]
Community version does not have full windows support. Also it is not optimized for training large models (it may require a lot of free memory while training).
You can try to run it on linux machine with 32 or better 64Gb memory, or you can purchase a **Pro** version.
