### ISSUE TITLE
What are minimum requirements?

### ISSUE THREAD

**Issue by ulziibadrakh-p** [bakwc/JamSpell#122]
1. Minimum requirements for training
2. Minimum requirements for run spell correction as a SAAS

**Comment by bakwc** [comment]
1. See [train documentation](https://jamspell.com/pro/w/train.html). You can skip all optional steps / parameters for minimum requirements.
2. See [HTTP API documentation](https://jamspell.com/pro/w/http_api.html)

**Comment by ulziibadrakh-p** [comment]
I have a pro version.
I have billion words dictionary and about 600mb text corpus.
What are technical requirements for this case? CPU, RAM etc.
Is it possible to train in windows machine? 
If it is possible, where can I see detailed instruction for windows?
