### ISSUE TITLE
How to train custom model?

### ISSUE THREAD

**Issue by Bananaspirit** [bakwc/JamSpell#124]
I don't understand how to train my own model. There is a section in the Readme that is responsible for training the model, but the files seem to be mixed up there, and this is more like testing the model.
`./main/jamspell train ../test_data/alphabet_en.txt ../test_data/sherlockholmes.txt model_sherlock.bin`
![image](https://user-images.githubusercontent.com/106806088/230072090-e6ce24dc-fc9d-4a24-9188-22c1d7ca2b34.png)

**Comment by bakwc** [comment]
Instead of test_data/scherlockholmes.txt you should add your own text file that should be used for training. What exactly don't you understand?
