### ISSUE TITLE
Is it yet alive?

### ISSUE THREAD

**Issue by sergeych** [bakwc/JamSpell#128]
[jamspell.com](https://jamspell.com/) seems to be down. Open source version seems to be abandoned in favor of commercial one and does not actually usable (as not cross-platoform). So, is it dead?

**Comment by bakwc** [comment]
* Support for existing customers is performed by e-mail support@jamspell.com
 * Commercial version selling is temporary suspended, will be resumed in the future
 * Open source version is not cross-platform, as a workaround you can use it inside docker for non-Linux OS.

**Comment by sergeych** [comment]
Well hope it will be back or better be free for non-commercial open source
software. Docker is not suitable for our needs so we had to look for other
variants, not that sleek but free and embeddable, like LT. pity on that.
Thanks for clarifying!
