### ISSUE TITLE
Is there a way to add new words to a dictionary without retraining a model?

### ISSUE THREAD

**Issue by antonshilov** [bakwc/JamSpell#18]
I want to add new words in run-time. How can I do that?

**Comment by sayak1711** [comment]
Hi
So how to do it? Have you added it? Is incremental learning possible?
Thanks

**Comment by bakwc** [comment]
Added in "Pro" version. It has incremental training ability, also it has ability to add sentences or single words at runtime, just call `corrector.AddText("your new text");`
JamSpellPro is available at [jamspell.com](https://jamspell.com/)
