### ISSUE TITLE
Quality falling on large model

### ISSUE THREAD

**Issue by bakwc** [bakwc/JamSpell#19]
There is a report about falling quality while training model on a large dataset (1/4 wikipedia). Need to reproduce, check if this is text-related issue or something wrong with the model.

**Comment by stephsamson** [comment]
I also encountered the same problem when training using all of the text data from the [Open American National Corpus](http://www.anc.org/data/oanc/download/). The error rate is `3.90 %` for Jamspell when using the `test_data/sherlockholmes.txt` as test data included in the repo.

**Comment by avostryakov** [comment]
The same problem with UMBC corpus (take random 5 million sentences 1/4 of UMBC).

**Comment by bakwc** [comment]
There is a two problems here.
1) Open American National Corpus does not have a "literature" subcorpus. To achieve best accuracy your dataset should includes a texts, simmilar to your production / test dataset.
2) Current version has a fixes coefficients, that are manually tuned for medium-size models (~80Mb text size).

You cat try "Pro" version. It is trained on a larged mixed corpus, which includes subtitles, literature, wikipedia and news, total size of train data is ~2Gb.
Also "pro" version has a [catboost](https://catboost.ai) classifier instead of a fixed coefficients and a reduced memory consumption, that allows JamSpellPro to handle models of any sizes.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
