### ISSUE TITLE
Ignore some words

### ISSUE THREAD

**Issue by stephsamson** [bakwc/JamSpell#20]
Some words, usually entities (product names, organization names, etc), are autocorrected. It would be nice if we could pass in a list of words to the corrector to be ignored.

**Comment by antonshilov** [comment]
Hello! Maybe you can put these words to the training dataset, so they will be counted as the correct words?

**Comment by stephsamson** [comment]
@antonshilov yup that's what I ended up doing and it works beautifully :)
