### ISSUE TITLE
What is the correct approach to handling letter case?

### ISSUE THREAD

**Issue by iosadchiy** [bakwc/JamSpell#25]
Thank you for the awesome library! Could you clarify if I'm using it correctly?

For now it does not handle letter case as I'd like. First, I'm trying to correct a typo in the word "best":

```
corrector.GetCandidates(['begt'], 0)
# ('best', 'beat', 'belt', 'bet', 'bent', 'beg', 'beet', 'begs', 'bert', 'beit', 'begt', 'begu', 'bengt', 'begat', 'beget')
```
It's perfect. But what if the word starts with an upper case letter:
```
corrector.GetCandidates(['Begt'], 0)
# ('get', 'set', 'left', 'next', 'best', 'west', 'went', 'east', 'got', 'yet', 'sent', 'eight', 'let', 'test', 'Begt')
```
Suggestions seem to be completely off.

Should it be my responsibility to lower everything and then restore case? Can it be solved by training the model on a larger data set?

**Comment by bakwc** [comment]
Yep, currently for GetCandidates you should make it lower and normalize (remove bad symbols) yourself. Training on a larger data set won't help here.

**Comment by iosadchiy** [comment]
OK, thanks
