### ISSUE TITLE
Failure of installation in Google Colab

### ISSUE THREAD

**Issue by happypetewht** [bakwc/JamSpell#32]
I tried to install Jamspell in Google Colab. But it shows this error. I used Python 3 and GPU

File "/tmp/pip-install-torr9p4t/jamspell/setup.py", line 45, in find_swig
        assert swigBinary is not None
    AssertionError
    
    ----------------------------------------

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-torr9p4t/jamspell/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ws9l_rnc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-torr9p4t/jamspell/

**Comment by happypetewht** [comment]
A follow up question: How can I install swig3 in Google colab? I searched online and it seems no article about it. It would be same as installation of other python packages? I tried that but failed too. I also searched swig3 in the root directory. No swig3 files. Thanks in advance.

**Comment by bakwc** [comment]
It is a binary package, usually it is installed from your distributive repository (`apt-get install swig3` or something like this)
