### ISSUE TITLE
Unable to produce results (C++)

### ISSUE THREAD

**Issue by williamgrosset** [bakwc/JamSpell#35]
I am unable to produce any errors with `FixFragment()` or `GetCandidates()`. I have done the following:

1. Added both `jamspell/` and `contrib/` directories to my project and included the header file.
2. Added the following lines to my `main`:
```cpp
NJamSpell::TSpellCorrector corrector;
corrector.LoadLangModel("model.bin");

std::string msg = NJamSpell::WideToUTF8(corrector.FixFragment(L"I am the begt spell cherken!"));
```
3. `msg` results in: `"I am the begt spell cherken!"`.

If I add any other string to `LoadLangModel("model.bin")`, no error is produced. Have I not imported the files correctly?

Thanks again for this repository (and including benchmarks against other tools). Cheers!

**Comment by kuraga** [comment]
@williamgrosset , did you fix it?
