### ISSUE TITLE
std::bad_alloc on jamspell train

### ISSUE THREAD

**Issue by rominf** [bakwc/JamSpell#43]
I downloaded latest Wikipedia dump, extracted plain text from it and got 12 GiB text file. I ran a training and got an error:
```[info] loading text
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I've checked the memory and verified, that I have it enough.

**Comment by valerius21** [comment]
You probably do not have enough ram. A 511 MB text file of mine used in the training process about 10 GB of ram. I'd recommend stripping down the samples and temporarily rent a performative server.

**Comment by bakwc** [comment]
1) Try to increase swap
2) Try JamSpellPro - it has optimization of memory consumption while training.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
