### ISSUE TITLE
HTTP API: seems both methods "fix" and "candidate" don't return expected results with russian words

### ISSUE THREAD

**Issue by shadow1512** [bakwc/JamSpell#45]
I trained a model with default kapitanskaya_dochka.txt (also tried with Anna Karenina and collection of 160 000+ russian words) and russian alphabet file. I started HTTP server with these models and used both GET and POST methods via console (in UTF-8: curl -d "ствкан" http://localhost:8080/candidates or curl -d "синтябрь" http://localhost:8080/fix) and via PHP test script (also in UTF-8). 
The server responded but with empty candidates array.

UPD: Also tried downloaded model (ru_small.bin) with the same result. After all tried English one - the same result. So, it looks like the server is working and responding, but always failed with answer.

Ubuntu 16.04

**Comment by bakwc** [comment]
Checked, everything works fine. You need to wait while model loaded.
