### ISSUE TITLE
Readme File Typo

### ISSUE THREAD

**Issue by imShayan** [bakwc/JamSpell#47]
A small typo in readme file which is not at all noticeable always. Please fix this.

`python evaluate/evalute.py -a alphabet_file.txt -jsp your_model.bin -mx 50000 your_test_data.txt`

the spelling of evaluate is wrong here, surprisingly it caused me a lil pain. 

Since the file generated is evaluate.py and not evalute.py.

`python evaluate/evaluate.py -a alphabet_file.txt -jsp your_model.bin -mx 50000 your_test_data.txt`

**Comment by bakwc** [comment]
Fixed

**Comment by imShayan** [comment]
you are welcome...!
