### ISSUE TITLE
[Enhancement] Pre-Trained Model for the german language

### ISSUE THREAD

**Issue by valerius21** [bakwc/JamSpell#49]
Hey, I am working on an enhanced spell check app. It's all in German. I used the recommended training data from the Leipzig University and merged all usable data. 
I trained as described in the Readme.md with ~5 million sentences on a high performance server.
May some of you guys find this useful.
## Alphabet
`abcdefghijklmnopqrstuvwxyzäöüß`
## Log
```
valerius@ubuntu-s-20vcpu-96gb-fra1-01:~/code/JamSpell/build/main$ python3 ~/code/JamSpell/evaluate/evaluate.py -a ./alphabet_ger.txt -jsp trained_ger.bin -mx 50000 ~/AUTO/TEXT/test.txt 
[info] loading models
[info] loading text
[info] generating typos
[info] total words: 76209
[info] evaluating
[debug] jamspell: processed 20.48%, error rate: 2.14%
[debug] jamspell: processed 40.73%, error rate: 2.21%
[debug] jamspell: processed 60.67%, error rate: 2.18%
[debug] jamspell: processed 79.80%, error rate: 2.13%
[debug] jamspell: processed 98.61%, error rate: 2.14%

[info]               errRate   fixRate    broken   topNerr   topNfix      time
[info]   jamspell      2.13%    86.79%     0.04%     1.16%    88.09%    20.32s
[info]      dummy     15.92%     0.00%     0.00%    15.92%     0.00% #    0.07s
```

## Download
[trained_ger.bin (431.7 MB)](https://mega.nz/#!sqAU1YJD!xhPc8u__d87AJhLcHj9MOb9B6tROB9JtkKTVJ5PgYuw)

**Comment by avostryakov** [comment]
@valerius21 Can you upload this file again, please! We need exactly German language

**Comment by valerius21** [comment]
I'm sorry. I don't have any backups left.

**Comment by bakwc** [comment]
`Pro` version has a big model for german language, along with source data.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)

**Comment by prabhakarsharma360** [comment]
> `Pro` version has a big model for german language, along with source data.
> 
> JamSpellPro is available at [jamspell.com](https://jamspell.com/)

Hi @bakwc, I only need the German model for my individual project, and buying a complete subscription is not possible. Can you provide the German Language model at a separate price? It will be a great help.

**Comment by bakwc** [comment]
You could reach by email at `contact` at `jamspell.com`
