### ISSUE TITLE
How much memory do I need to train a model?

### ISSUE THREAD

**Issue by avostryakov** [bakwc/JamSpell#5]
I tried to train on whole Russian wikipedia dump (~1.3 mln articles). The program crashed after couple of minutes:

./main/jamspell train alphabet_ru.txt wiki_ru.txt model_wiki.bin
[info] loading text
terminate called after throwing an instance of 'std:bad_alloc'
...
Aborted (core dump)

Ubuntu 16.04 with 32GB memory. Will 64GB be enough to train?

**Comment by bakwc** [comment]
Not sure, have not tested it on such big models. You can try to use some part to check.

**Comment by avostryakov** [comment]
Sorry, one more question: should I tokenize, lowercasing text before training. Without lowercasing should I add uppercase letters in alphabet-file?

**Comment by bakwc** [comment]
> should I tokenize, lowercasing text before training

No, lowering is done automatically while training.

> Without lowercasing should I add uppercase letters in alphabet-file

Currently there is no ability to train with upper-case (in my expericense there was no quality improving when using lower + upper case).

**Comment by avostryakov** [comment]
What about tokenization and sentence splitting?

**Comment by bakwc** [comment]
It is also done automatically for training, you should leave `!?.` in original text.
