### ISSUE TITLE
Jamspell not able to train model for corpus larger than a certain size

### ISSUE THREAD

**Issue by sayak1711** [bakwc/JamSpell#51]
Hi
Jamspell throws error and stops when trying to read a 15.3 GB file for training. It however doesn't fail for other files of much smaller size.

```
./main/jamspell train ../test_data/alphabet_en.txt ../test_data/combined.txt model_combined.bin
[info] loading text
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by ademyanchuk** [comment]
Same issue, but on just 1.8 GB. Any workarounds?

**Comment by Desklop** [comment]
Такая же ошибка на корпусе в 350мб, есть какое-нибудь решение?

**Comment by bakwc** [comment]
можно свап попробовать врубить

**Comment by Niecke** [comment]
Just as a small benchmark: It looks like for a 15GB txt file as input, you need about 300GB RAM while loading and about 50 GB RAM while processing. I don't know if these values are influenced by the OS or anything else.

**Comment by loretoparisi** [comment]
@Niecke thanks for this benchmarks. So basically it's pretty hard to train a new model outside a scalable infrastructure like AWS EC2 instances, etc. I mean I do not have a 300GB RAM Xeon under my desk :D

**Comment by bakwc** [comment]
1) Try to increase swap
2) Try a new "JamSpellPro" version. It has optimization for training large model (it use only 1/2 of original memory usage).

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
