### ISSUE TITLE
Differentiate unknown words in spell checker output

### ISSUE THREAD

**Issue by subhash-velou** [bakwc/JamSpell#54]
Is there a way to differentiate between words that are unknown to the dictionary? For example, in the sentence below "table" is a correctly spelled word; "xyz" is a completely unknown word; "clth" is a misspelled word (I get candidates for this - all good). The issue I'm currently facing is there is no way to know what words are correctly spelled vs unknown.
`$ curl "http://localhost:8081/candidates?text=table xyz clth"
{
    "results": [
        {
            "candidates": [
                "cloth",
                "cath",
                "clth",
                "clt1"
            ],
            "len": 4,
            "pos_from": 10
        }
    ]
}`

Any thoughts?

**Comment by bakwc** [comment]
If you still interested - we can add this feature to a `Pro` version. Reach us at `support@jamspell.com`.
