### ISSUE TITLE
Model created on Linux doesn't load on Windows

### ISSUE THREAD

**Issue by sayak1711** [bakwc/JamSpell#56]
I have run Jamspell on RHEL, Ubuntu and Windows.
The models we create on Windows can be loaded there however models created on other OS can't be loaded on Windows machine. Since my Windows machine doesn't have as much ram as the linux ones this is a problem for me.

**Comment by bakwc** [comment]
Fixed in "Pro" version. "Pro" version is fully cross-platform, works on windows / mac / linux / mobile devices.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
