### ISSUE TITLE
Error in handypack.hpp while installing Jamspell

### ISSUE THREAD

**Issue by salonisheth** [bakwc/JamSpell#57]
Hi, Im trying to install Jamspell on Windows 10, Python 2.7. I am getting syntax errors from one the source files that is within jamspell - handypack.hpp. See the full stack trace below.

Collecting jamspell
  Using cached https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz
Building wheels for collected packages: jamspell
  Running setup.py bdist_wheel for jamspell ... error
  Complete output from command C:\ProgramData\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\sasheth\\appdata\\local\\temp\\pip-build-1pszkn\\jamspell\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\sasheth\appdata\local\temp\tmpwm3e0ypip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  swigging jamspell.i to jamspell_wrap.cpp
  C:\swigwin-3.0.12\swig.exe -python -c++ -o jamspell_wrap.cpp jamspell.i
  creating build
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\jamspell
  creating build\temp.win32-2.7\Release\contrib
  creating build\temp.win32-2.7\Release\contrib\cityhash
  creating build\temp.win32-2.7\Release\contrib\phf
  C:\Users\sasheth\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -Ijamspell -IC:\ProgramData\Anaconda2\include -IC:\ProgramData\Anaconda2\PC /Tpjamspell\lang_model.cpp /Fobuild\temp.win32-2.7\Release\jamspell\lang_model.obj -std=c++11 -O2
  cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
  lang_model.cpp
  C:\Users\sasheth\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
  .\contrib/handypack/handypack.hpp(72) : error C2332: 'class' : missing tag name
  .\contrib/handypack/handypack.hpp(72) : error C2993: '' : illegal type for non-type template parameter '<unnamed-tag>'
  .\contrib/handypack/handypack.hpp(72) : error C2143: syntax error : missing ',' before '...'
  .\contrib/handypack/handypack.hpp(73) : error C2039: 'tuple' : is not a member of 'std'
  .\contrib/handypack/handypack.hpp(73) : error C2065: 'tuple' : undeclared identifier
  .\contrib/handypack/handypack.hpp(73) : error C2065: 'Args' : undeclared identifier
  .\contrib/handypack/handypack.hpp(73) : error C2143: syntax error : missing ',' before '...'
  .\contrib/handypack/handypack.hpp(73) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(75) : error C2039: 'tuple' : is not a member of 'std'
  .\contrib/handypack/handypack.hpp(75) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(76) : error C2065: 'object' : undeclared identifier
  .\contrib/handypack/handypack.hpp(76) : error C2059: syntax error : '...'
  .\contrib/handypack/handypack.hpp(76) : error C2059: syntax error : ')'
  .\contrib/handypack/handypack.hpp(77) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(78) : error C2039: 'tuple' : is not a member of 'std'
  .\contrib/handypack/handypack.hpp(78) : error C2065: 'tuple' : undeclared identifier
  .\contrib/handypack/handypack.hpp(78) : error C2065: 'Args' : undeclared identifier
  .\contrib/handypack/handypack.hpp(78) : error C2143: syntax error : missing ',' before '...'
  .\contrib/handypack/handypack.hpp(78) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(79) : error C2065: 'object' : undeclared identifier
  .\contrib/handypack/handypack.hpp(79) : error C2059: syntax error : '...'
  .\contrib/handypack/handypack.hpp(79) : error C2059: syntax error : ')'
  .\contrib/handypack/handypack.hpp(80) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(81) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(83) : error C2947: expecting '>' to terminate template-argument-list, found '>'
  .\contrib/handypack/handypack.hpp(83) : error C2975: 'NHandyPack::int_' : invalid template argument for 'unnamed-parameter', expected compile-time constant expression
          .\contrib/handypack/handypack.hpp(48) : see declaration of 'NHandyPack::int_'
  .\contrib/handypack/handypack.hpp(84) : error C2236: unexpected 'class' 'TVectorSerializer'. Did you forget a ';'?
  .\contrib/handypack/handypack.hpp(84) : error C2143: syntax error : missing ')' before '{'
  .\contrib/handypack/handypack.hpp(84) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(84) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(86) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(88) : error C2065: 'size' : undeclared identifier
  .\contrib/handypack/handypack.hpp(88) : error C2070: ''unknown-type'': illegal sizeof operand
  .\contrib/handypack/handypack.hpp(88) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(89) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(90) : error C2065: 'obj' : undeclared identifier
  .\contrib/handypack/handypack.hpp(91) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(92) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(94) : error C2065: 'TVec' : undeclared identifier
  .\contrib/handypack/handypack.hpp(94) : error C2065: 'object' : undeclared identifier
  .\contrib/handypack/handypack.hpp(94) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(94) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(96) : error C2065: 'size' : undeclared identifier
  .\contrib/handypack/handypack.hpp(96) : error C2070: ''unknown-type'': illegal sizeof operand
  .\contrib/handypack/handypack.hpp(96) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(99) : error C2143: syntax error : missing ')' before ';'
  .\contrib/handypack/handypack.hpp(99) : error C2059: syntax error : ')'
  .\contrib/handypack/handypack.hpp(99) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(101) : error C2065: 'obj' : undeclared identifier
  .\contrib/handypack/handypack.hpp(102) : error C2039: 'move' : is not a member of 'std'
  .\contrib/handypack/handypack.hpp(103) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(104) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(105) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(107) : error C2947: expecting '>' to terminate template-argument-list, found '>'
  .\contrib/handypack/handypack.hpp(107) : error C2977: 'NHandyPack::int_' : too many template arguments
          .\contrib/handypack/handypack.hpp(48) : see declaration of 'NHandyPack::int_'
  .\contrib/handypack/handypack.hpp(108) : error C2236: unexpected 'class' 'TMapSerializer'. Did you forget a ';'?
  .\contrib/handypack/handypack.hpp(108) : error C2143: syntax error : missing ')' before '{'
  .\contrib/handypack/handypack.hpp(108) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(108) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(110) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(112) : error C2065: 'size' : undeclared identifier
  .\contrib/handypack/handypack.hpp(112) : error C2070: ''unknown-type'': illegal sizeof operand
  .\contrib/handypack/handypack.hpp(112) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(113) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(114) : error C2065: 'obj' : undeclared identifier
  .\contrib/handypack/handypack.hpp(115) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(116) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(118) : error C2065: 'TVec' : undeclared identifier
  .\contrib/handypack/handypack.hpp(118) : error C2065: 'object' : undeclared identifier
  .\contrib/handypack/handypack.hpp(118) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(118) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(120) : error C2065: 'size' : undeclared identifier
  .\contrib/handypack/handypack.hpp(120) : error C2070: ''unknown-type'': illegal sizeof operand
  .\contrib/handypack/handypack.hpp(120) : error C2143: syntax error : missing ',' before ')'
  .\contrib/handypack/handypack.hpp(122) : error C2143: syntax error : missing ')' before ';'
  .\contrib/handypack/handypack.hpp(122) : error C2059: syntax error : ')'
  .\contrib/handypack/handypack.hpp(122) : error C2143: syntax error : missing ';' before '{'
  .\contrib/handypack/handypack.hpp(124) : error C2065: 'obj' : undeclared identifier
  .\contrib/handypack/handypack.hpp(125) : error C2039: 'move' : is not a member of 'std'
  .\contrib/handypack/handypack.hpp(126) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(127) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(128) : error C2143: syntax error : missing ';' before '}'
  .\contrib/handypack/handypack.hpp(130) : error C2947: expecting '>' to terminate template-argument-list, found '>'
  .\contrib/handypack/handypack.hpp(152) : error C2236: unexpected 'class' 'NHandyPack::TUnorderedMapSerializer'. Did you forget a ';'?
  .\contrib/handypack/handypack.hpp(152) : error C3381: 'NHandyPack::TUnorderedMapSerializer' : assembly access specifiers are only available in code compiled with a /clr option
  .\contrib/handypack/handypack.hpp(177) : error C2504: 'TVectorSerializer' : base class undefined
          .\contrib/handypack/handypack.hpp(177) : see reference to class template instantiation 'NHandyPack::TSerializer<std::vector<T>>' being compiled
  .\contrib/handypack/handypack.hpp(177) : error C2143: syntax error : missing ',' before '<'
  .\contrib/handypack/handypack.hpp(178) : error C2504: 'TVectorSerializer' : base class undefined
          .\contrib/handypack/handypack.hpp(178) : see reference to class template instantiation 'NHandyPack::TSerializer<std::list<T>>' being compiled
  .\contrib/handypack/handypack.hpp(178) : error C2143: syntax error : missing ',' before '<'
  .\contrib/handypack/handypack.hpp(179) : error C2504: 'TVectorSerializer' : base class undefined
  .\contrib/handypack/handypack.hpp(179) : error C2143: syntax error : missing ',' before '<'
  .\contrib/handypack/handypack.hpp(180) : error C2504: 'TVectorSerializer' : base class undefined
  .\contrib/handypack/handypack.hpp(180) : error C2143: syntax error : missing ',' before '<'
  .\contrib/handypack/handypack.hpp(181) : error C2504: 'TMapSerializer' : base class undefined
          .\contrib/handypack/handypack.hpp(181) : see reference to class template instantiation 'NHandyPack::TSerializer<std::map<K,V>>' being compiled
  .\contrib/handypack/handypack.hpp(181) : error C2143: syntax error : missing ',' before '<'
  .\contrib/handypack/handypack.hpp(182) : error C2039: 'unordered_map' : is not a member of 'std'
  .\contrib/handypack/handypack.hpp(182) : error C2065: 'unordered_map' : undeclared identifier
  .\contrib/handypack/handypack.hpp(182) : error C2977: 'NHandyPack::TSerializer' : too many template arguments
          .\contrib/handypack/handypack.hpp(18) : see declaration of 'NHandyPack::TSerializer'
  .\contrib/handypack/handypack.hpp(182) : error C2143: syntax error : missing ';' before '>'
  .\contrib/handypack/handypack.hpp(182) : error C2977: 'NHandyPack::TSerializer' : too many template arguments
          .\contrib/handypack/handypack.hpp(18) : see declaration of 'NHandyPack::TSerializer'
  .\contrib/handypack/handypack.hpp(182) : error C2059: syntax error : '>'
  .\contrib/handypack/handypack.hpp(182) : fatal error C1003: error count exceeds 100; stopping compilation
  error: command 'C:\\Users\\sasheth\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
  Running setup.py install for jamspell ... error
    Complete output from command C:\ProgramData\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\sasheth\\appdata\\local\\temp\\pip-build-1pszkn\\jamspell\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\sasheth\appdata\local\temp\pip-acckgt-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_jamspell' extension
    swigging jamspell.i to jamspell_wrap.cpp
    C:\swigwin-3.0.12\swig.exe -python -c++ -o jamspell_wrap.cpp jamspell.i
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\jamspell
    creating build\temp.win32-2.7\Release\contrib
    creating build\temp.win32-2.7\Release\contrib\cityhash
    creating build\temp.win32-2.7\Release\contrib\phf
    C:\Users\sasheth\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I. -Ijamspell -IC:\ProgramData\Anaconda2\include -IC:\ProgramData\Anaconda2\PC /Tpjamspell\lang_model.cpp /Fobuild\temp.win32-2.7\Release\jamspell\lang_model.obj -std=c++11 -O2
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    lang_model.cpp
    C:\Users\sasheth\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
    .\contrib/handypack/handypack.hpp(72) : error C2332: 'class' : missing tag name
    .\contrib/handypack/handypack.hpp(72) : error C2993: '' : illegal type for non-type template parameter '<unnamed-tag>'
    .\contrib/handypack/handypack.hpp(72) : error C2143: syntax error : missing ',' before '...'
    .\contrib/handypack/handypack.hpp(73) : error C2039: 'tuple' : is not a member of 'std'
    .\contrib/handypack/handypack.hpp(73) : error C2065: 'tuple' : undeclared identifier
    .\contrib/handypack/handypack.hpp(73) : error C2065: 'Args' : undeclared identifier
    .\contrib/handypack/handypack.hpp(73) : error C2143: syntax error : missing ',' before '...'
    .\contrib/handypack/handypack.hpp(73) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(75) : error C2039: 'tuple' : is not a member of 'std'
    .\contrib/handypack/handypack.hpp(75) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(76) : error C2065: 'object' : undeclared identifier
    .\contrib/handypack/handypack.hpp(76) : error C2059: syntax error : '...'
    .\contrib/handypack/handypack.hpp(76) : error C2059: syntax error : ')'
    .\contrib/handypack/handypack.hpp(77) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(78) : error C2039: 'tuple' : is not a member of 'std'
    .\contrib/handypack/handypack.hpp(78) : error C2065: 'tuple' : undeclared identifier
    .\contrib/handypack/handypack.hpp(78) : error C2065: 'Args' : undeclared identifier
    .\contrib/handypack/handypack.hpp(78) : error C2143: syntax error : missing ',' before '...'
    .\contrib/handypack/handypack.hpp(78) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(79) : error C2065: 'object' : undeclared identifier
    .\contrib/handypack/handypack.hpp(79) : error C2059: syntax error : '...'
    .\contrib/handypack/handypack.hpp(79) : error C2059: syntax error : ')'
    .\contrib/handypack/handypack.hpp(80) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(81) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(83) : error C2947: expecting '>' to terminate template-argument-list, found '>'
    .\contrib/handypack/handypack.hpp(83) : error C2975: 'NHandyPack::int_' : invalid template argument for 'unnamed-parameter', expected compile-time constant expression
            .\contrib/handypack/handypack.hpp(48) : see declaration of 'NHandyPack::int_'
    .\contrib/handypack/handypack.hpp(84) : error C2236: unexpected 'class' 'TVectorSerializer'. Did you forget a ';'?
    .\contrib/handypack/handypack.hpp(84) : error C2143: syntax error : missing ')' before '{'
    .\contrib/handypack/handypack.hpp(84) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(84) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(86) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(88) : error C2065: 'size' : undeclared identifier
    .\contrib/handypack/handypack.hpp(88) : error C2070: ''unknown-type'': illegal sizeof operand
    .\contrib/handypack/handypack.hpp(88) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(89) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(90) : error C2065: 'obj' : undeclared identifier
    .\contrib/handypack/handypack.hpp(91) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(92) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(94) : error C2065: 'TVec' : undeclared identifier
    .\contrib/handypack/handypack.hpp(94) : error C2065: 'object' : undeclared identifier
    .\contrib/handypack/handypack.hpp(94) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(94) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(96) : error C2065: 'size' : undeclared identifier
    .\contrib/handypack/handypack.hpp(96) : error C2070: ''unknown-type'': illegal sizeof operand
    .\contrib/handypack/handypack.hpp(96) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(99) : error C2143: syntax error : missing ')' before ';'
    .\contrib/handypack/handypack.hpp(99) : error C2059: syntax error : ')'
    .\contrib/handypack/handypack.hpp(99) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(101) : error C2065: 'obj' : undeclared identifier
    .\contrib/handypack/handypack.hpp(102) : error C2039: 'move' : is not a member of 'std'
    .\contrib/handypack/handypack.hpp(103) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(104) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(105) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(107) : error C2947: expecting '>' to terminate template-argument-list, found '>'
    .\contrib/handypack/handypack.hpp(107) : error C2977: 'NHandyPack::int_' : too many template arguments
            .\contrib/handypack/handypack.hpp(48) : see declaration of 'NHandyPack::int_'
    .\contrib/handypack/handypack.hpp(108) : error C2236: unexpected 'class' 'TMapSerializer'. Did you forget a ';'?
    .\contrib/handypack/handypack.hpp(108) : error C2143: syntax error : missing ')' before '{'
    .\contrib/handypack/handypack.hpp(108) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(108) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(110) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(112) : error C2065: 'size' : undeclared identifier
    .\contrib/handypack/handypack.hpp(112) : error C2070: ''unknown-type'': illegal sizeof operand
    .\contrib/handypack/handypack.hpp(112) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(113) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(114) : error C2065: 'obj' : undeclared identifier
    .\contrib/handypack/handypack.hpp(115) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(116) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(118) : error C2065: 'TVec' : undeclared identifier
    .\contrib/handypack/handypack.hpp(118) : error C2065: 'object' : undeclared identifier
    .\contrib/handypack/handypack.hpp(118) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(118) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(120) : error C2065: 'size' : undeclared identifier
    .\contrib/handypack/handypack.hpp(120) : error C2070: ''unknown-type'': illegal sizeof operand
    .\contrib/handypack/handypack.hpp(120) : error C2143: syntax error : missing ',' before ')'
    .\contrib/handypack/handypack.hpp(122) : error C2143: syntax error : missing ')' before ';'
    .\contrib/handypack/handypack.hpp(122) : error C2059: syntax error : ')'
    .\contrib/handypack/handypack.hpp(122) : error C2143: syntax error : missing ';' before '{'
    .\contrib/handypack/handypack.hpp(124) : error C2065: 'obj' : undeclared identifier
    .\contrib/handypack/handypack.hpp(125) : error C2039: 'move' : is not a member of 'std'
    .\contrib/handypack/handypack.hpp(126) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(127) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(128) : error C2143: syntax error : missing ';' before '}'
    .\contrib/handypack/handypack.hpp(130) : error C2947: expecting '>' to terminate template-argument-list, found '>'
    .\contrib/handypack/handypack.hpp(152) : error C2236: unexpected 'class' 'NHandyPack::TUnorderedMapSerializer'. Did you forget a ';'?
    .\contrib/handypack/handypack.hpp(152) : error C3381: 'NHandyPack::TUnorderedMapSerializer' : assembly access specifiers are only available in code compiled with a /clr option
    .\contrib/handypack/handypack.hpp(177) : error C2504: 'TVectorSerializer' : base class undefined
            .\contrib/handypack/handypack.hpp(177) : see reference to class template instantiation 'NHandyPack::TSerializer<std::vector<T>>' being compiled
    .\contrib/handypack/handypack.hpp(177) : error C2143: syntax error : missing ',' before '<'
    .\contrib/handypack/handypack.hpp(178) : error C2504: 'TVectorSerializer' : base class undefined
            .\contrib/handypack/handypack.hpp(178) : see reference to class template instantiation 'NHandyPack::TSerializer<std::list<T>>' being compiled
    .\contrib/handypack/handypack.hpp(178) : error C2143: syntax error : missing ',' before '<'
    .\contrib/handypack/handypack.hpp(179) : error C2504: 'TVectorSerializer' : base class undefined
    .\contrib/handypack/handypack.hpp(179) : error C2143: syntax error : missing ',' before '<'
    .\contrib/handypack/handypack.hpp(180) : error C2504: 'TVectorSerializer' : base class undefined
    .\contrib/handypack/handypack.hpp(180) : error C2143: syntax error : missing ',' before '<'
    .\contrib/handypack/handypack.hpp(181) : error C2504: 'TMapSerializer' : base class undefined
            .\contrib/handypack/handypack.hpp(181) : see reference to class template instantiation 'NHandyPack::TSerializer<std::map<K,V>>' being compiled
    .\contrib/handypack/handypack.hpp(181) : error C2143: syntax error : missing ',' before '<'
    .\contrib/handypack/handypack.hpp(182) : error C2039: 'unordered_map' : is not a member of 'std'
    .\contrib/handypack/handypack.hpp(182) : error C2065: 'unordered_map' : undeclared identifier
    .\contrib/handypack/handypack.hpp(182) : error C2977: 'NHandyPack::TSerializer' : too many template arguments
            .\contrib/handypack/handypack.hpp(18) : see declaration of 'NHandyPack::TSerializer'
    .\contrib/handypack/handypack.hpp(182) : error C2143: syntax error : missing ';' before '>'
    .\contrib/handypack/handypack.hpp(182) : error C2977: 'NHandyPack::TSerializer' : too many template arguments
            .\contrib/handypack/handypack.hpp(18) : see declaration of 'NHandyPack::TSerializer'
    .\contrib/handypack/handypack.hpp(182) : error C2059: syntax error : '>'
    .\contrib/handypack/handypack.hpp(182) : fatal error C1003: error count exceeds 100; stopping compilation
    error: command 'C:\\Users\\sasheth\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\ProgramData\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\sasheth\\appdata\\local\\temp\\pip-build-1pszkn\\jamspell\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\sasheth\appdata\local\temp\pip-acckgt-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\sasheth\appdata\local\temp\pip-build-1pszkn\jamspell\

**Comment by bakwc** [comment]
Try a fresh MSVC compiler and a `Pro` version.

JamSpellPro successfully builds with MSVC Community 2019.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
