### ISSUE TITLE
Split words

### ISSUE THREAD

**Issue by ndvbd** [bakwc/JamSpell#8]
I noticed that the library doesn't split words, like in: "Can you readthis message?"

Will it have support for cross-word corrections?

**Comment by bakwc** [comment]
Yep, I'm working on it.

**Comment by antonshilov** [comment]
Hello, @bakwc! Thank you for a great project! Maybe you can find some useful ideas in the [SymSpellCompound ](https://github.com/wolfgarbe/SymSpellCompound) for the word compounding.

**Comment by bakwc** [comment]
This feature is implemented in "Pro" version. Pro version splits merged words.
JamSpellPro is available at [jamspell.com](https://jamspell.com/)
