### ISSUE TITLE
Optimal data structure for training?

### ISSUE THREAD

**Issue by SergShulga** [bakwc/JamSpell#84]
Добрый день, 

Как лучше сделать файл для обучения? 
На каждой строчке одно слово или предложения?
Надо ли убирать цифры, знаки препинания и специальные символы?
Можно ли допускать наличие слов на другом языке (указать при этом его в файле алфавита)?

Спасибо!

**Comment by bakwc** [comment]
Одна строка - одно предложение.
Можно делать много-языковую модель, однако модели заточенные под конкретный язык показывают лучшие результаты.
