### ISSUE TITLE
corrector.FixFragment doesn't change anything

### ISSUE THREAD

**Issue by SergShulga** [bakwc/JamSpell#85]
Test string contains bad words form train dataset.
**corrector.FixFragment** return string with misspelling without changes after training the Russian model on subtitles.

At the same time, **corrector.GetCandidates** returns possible candidates for a single word
What is the problem?

**Comment by kuraga** [comment]
@SergShulga , did you fix it?

**Comment by bakwc** [comment]
Could you provide train data, model and your queries? Looks like a bug, need more info to reproduce.
