### ISSUE TITLE
Is really jamspell support multiple languages?

### ISSUE THREAD

**Issue by VJAYSLN** [bakwc/JamSpell#86]
Hey there, 
I am working with your spellchecker for a last couple of months. Till now i am only working with **english.** Now, I should need other languages like _french, spanish, portuguese_ etc.,
Is really jamspell support for all those languages? If Yes, then How can i, load alphabet file, preprocessing text and do stuff related with various language alphabets.?

Thanks in Advance.,

**Comment by bakwc** [comment]
Hi,  VJAYSLN - you need to [train a model](https://github.com/bakwc/JamSpell#train) for that languages. Currently there is onlye EN, RU and FR pretrained models.

**Comment by VJAYSLN** [comment]
Thanks bakwc for quick response.
