### ISSUE TITLE
Spellchecker for multiple languages!!

### ISSUE THREAD

**Issue by VJAYSLN** [bakwc/JamSpell#87]
Hey there, 
I am working with your spellchecker for a last couple of months. Till now i am only working with **english.** . Now i wants spellchecker for all languages. As mentioned in your repo, spellchecker is support all languages. As in, Please figure out some of the questions? 
1. List of Languages are Supported by Jamspell?
2.Can u attach alphabet files for different languages that its supports? 
3.Is it support for CJK languages too? 

Thanks in Advance.,

**Comment by bakwc** [comment]
`JamSpellPro` has pre-trained models for `en, ru, de, fr, it, es, tr, uk, pl, nl, pt, hi, ur, no`. Also it includes alphabet files and source data (2Gb) for training your own models.
We can train `CJK` model for you if you purchase a `Pro` or `Enterprise` version.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
