### ISSUE TITLE
C++ code not working

### ISSUE THREAD

**Issue by VJAYSLN** [bakwc/JamSpell#88]
I have copied contrib and jamspell dirs in my project. And try to execute the code, which is given in the readme document.
`#include <jamspell/spell_corrector.hpp>

int main(int argc, const char** argv) {

    NJamSpell::TSpellCorrector corrector;
    corrector.LoadLangModel("model.bin");

    corrector.FixFragment(L"I am the begt spell cherken!");
    // "I am the best spell checker!"

    corrector.GetCandidates({L"i", L"am", L"the", L"begt", L"spell", L"cherken"}, 3);
    // "best", "beat", "belt", "bet", "bent", ... )

    corrector.GetCandidates({L"i", L"am", L"the", L"begt", L"spell", L"cherken"}, 3);
    // "checker", "chicken", "checked", "wherein", "coherent", ... )
    return 0;
}`
 
But I got a bunch of errors that shows `undefined reference to the function` . means that the function does not exist. Anyone help me to get through this : ( 
Thanks in Advance.

**Comment by ulziibadrakh-p** [comment]
Did you solve it?
