### ISSUE TITLE
Benchmarks: SymSpell

### ISSUE THREAD

**Issue by loretoparisi** [bakwc/JamSpell#89]
Thanks for this project. I would suggest to add benchmarks to wolfgarbe [SymSpell](https://github.com/wolfgarbe/SymSpell)

Thanks a lot!

**Comment by rprilepskiy** [comment]
It's worth to mention to use [test set](http://www.dialog-21.ru/media/3838/test_sample_testset.txt) for the [SpellRuEval competition](http://www.dialog-21.ru/en/evaluation/2016/spelling_correction/)  as a possible benchmark. Plus it would be great to compare (and use as ideas for improvement) different correction methods from [here](http://docs.deeppavlov.ai/en/master/features/models/spelling_correction.html#comparison).

**Comment by bakwc** [comment]
1) `SymSpell` does not consider word surroundings, so it has better speed, but less accuracy. JamSpell is for cases when you need a reasonably good speed and good accuracy.
2) `JamSpellPro` was benchmarked on `SpellRuEval`, it has following results:

|     checker|   errRate|   fixRate|    broken|       pr|        re|        f1|      time|
|--- |--- |--- |--- |--- |--- |--- |--- |
|     yandex|      2.20%|    62.96%|     0.21%|     94.44%|    62.96%|    **75.56%**|    17.67s|
|   jamspell|      2.50%|    64.81%|     0.63%|     85.37%|    64.81%|    **73.68%**|     3.90s|
|       bing|      4.20%|    24.07%|     0.11%|     92.86%|    24.07%|    **38.24%**|   110.78s|
|   hunspell|      6.70%|    29.63%|     3.07%|     35.56%|    29.63%|    **32.32%**|     8.00s|

Russian language, real world errors from [dialog-21 contest](http://www.dialog-21.ru/en/evaluation/2016/spelling_correction/)  
(*was used only 90% of test samples, 10% of dataset was not mapped by automatic rules).

**Comment by loretoparisi** [comment]
@bakwc thanks a lot! I have to say that difference in `f1` when using `hunspell` is impressive.

**Comment by bakwc** [comment]
This is a `Pro` version benchmark, with large model (~1.5Gb). Community version has slightly worse performance.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)

**Comment by loretoparisi** [comment]
@bakwc I see. Can be the `Pro` version used offline?

**Comment by bakwc** [comment]
Yes, full source code provided. Pro version has a limit for a company revenue (less than 200K USD annual), for larger companies there is enterprise license. I can provide a demo, you can write at `support@jamspell.com`
