### ISSUE TITLE
CAn we retrained the model with new data?

### ISSUE THREAD

**Issue by harsh-98** [bakwc/JamSpell#9]
If yes, can u provide an example, it would be really helpful.

**Comment by bakwc** [comment]
It is described in [Train](https://github.com/bakwc/JamSpell#train) section in README. Feel free to ask any question.

**Comment by harsh-98** [comment]
I mean to say that if I train a A.bin on databsetA and then I want to train B.bin  based on A.bin and datasetB so that the B.bin can correct the words in datasetA and datasetB. how should one train for this?

**Comment by harsh-98** [comment]
for example while  training on dataset on 300K wiki and 300Karticles u must have broken the dataset in subset and trained on them. Then somehow combined them into the final.bin.

**Comment by bakwc** [comment]
no, i combined datasets (using `evaluate/generate_dataset.py` util) and trained on a combined one

**Comment by bakwc** [comment]
> And if it is currently possible to do so
Currently that's not possible

> are you planning on implementing it
I'm not planning to implement this feature. But if you want - you can do it yourself, I will be glad to accept your pull-request. It's quite simple to implement - you just need to extand dictionary and sum word counts in language model.

**Comment by bakwc** [comment]
Implemented in "Pro" version. You can add a large corpus file or several sentences, or single words at runtime, without training a new model from scratch.
JamSpellPro is available at jamspell.com
