### ISSUE TITLE
Give a dictionary of words for spell correction

### ISSUE THREAD

**Issue by aastha19** [bakwc/JamSpell#95]
Hi,

I have trained a model on my dataset. Yet there are certain words that are not corrected properly. Is there a way to pass a dictionary (uncorrect->correct word pairs) during the time we call the FixFragment function.

**Comment by bakwc** [comment]
Hi, you can do it in `Pro` version with `corrector.AddText("word")` or `corrector.AddText("my new sentence")`.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
